SelectedArena: Bay
Season: NONE
MySQL:
  host: 10.0.4.53
  port: 3306
  database: jadedmc
  username: server
  password: wsxqaz
  useSSL: true

Parkour:
  GREEN:
    Name: '&aGreen'
    Location:
      World: world
      X: 3.5
      Y: 100
      Z: 343.5
      Yaw: 180
      Pitch: 0
  YELLOW:
    Name: '&eYellow'
    Location:
      World: world
      X: 32.5
      Y: 100
      Z: 333.5
      Yaw: -90
      Pitch: 0
  RED:
    Name: '&cRed'
    Location:
      World: world
      X: 87.5
      Y: 101
      Z: 342.5
      Yaw: -90
      Pitch: 0
  BLUE:
    Name: '&9Blue'
    Location:
      World: world
      X: 140.5
      Y: 100
      Z: 333.5
      Yaw: -90
      Pitch: 0
  BEGINNER:
    Name: '&cBeginner'
    Location:
      World: world
      X: 27.5
      Y: 114.05
      Z: 427.5
      Yaw: -90
      Pitch: 0
  ADVANCED:
    Name: '&5Advanced'
    Location:
      World: world
      X: 163.5
      Y: 116
      Z: 416.5
      Yaw: -180
      Pitch: 0
  PEERLESS:
    Name: '&9Peerless'
    Location:
      World: world
      X: 81.5
      Y: 103
      Z: 397.5
      Yaw: -90
      Pitch: 0
