name: ElytraPvP
version: '${project.version}'
main: net.jadedmc.elytrapvp.ElytraPvP
api-version: 1.19
authors: [ JadedMC ]
website: http://www.jadedmc.net

depend:
  - PlaceholderAPI

softdepend:
  - DiscordSRV

commands:
  arena:
    description: Manages arenas
    usage: /arena
    aliases: [arenas]
  bounty:
    description: Manages bounty commands.
    usage: /bounty
  cosmetics:
    description: Open the cosmetics menu.
    usage: /cosmetics.
  kits:
    description: Opens the kit selector menu.
    usage: /kits
  leaderboard:
    description: View the server leaderboards.
    usage: /<command>
    aliases: [lb,top,best]
  parkour:
    description: Runs the parkour system.
    usage: /parkour
  settings:
    description: Opens the setting menu.
    usage: /settings
  spawn:
    description: Teleports back to the arena spawn.
    usage: /spawn
  stats:
    description: View the player's stats.
    usage: /stats