name: ElytraPvP
version: '${project.version}'
main: net.jadedmc.elytrapvp.ElytraPvP
api-version: 1.19
authors: [ JadedMC ]
website: http://www.jadedmc.net

softdepend:
  - DiscordSRV

commands:
  arena:
    description: Manages arenas
    usage: /arena
    aliases: [arenas]
  kits:
    description: Opens the kit selector menu.
    usage: /kits
  settings:
    description: Opens the setting menu.
    usage: /settings
  spawn:
    description: Teleports back to the arena spawn.
    usage: /spawn